package com.example.ping_pong_frontend.databinding

// This file exists only to ensure the package compiles without IDE.
// Actual classes ActivityMainBinding and ActivitySettingsBinding are generated by the Android Gradle plugin at build time.
